param(
  [string]$ProjectRoot=(Get-Location).Path
)

$ErrorActionPreference="Stop"
Set-StrictMode -Version Latest

$ProjectRoot=(Resolve-Path -LiteralPath $ProjectRoot).Path
$State=Join-Path $ProjectRoot "PROJECT_STATE"
$Audit=Join-Path $ProjectRoot "audit_exports"
$Milestones=Join-Path $State "milestones"
$PackageDir=Join-Path $State "guarded_rotation_canary_package_v1"

New-Item -ItemType Directory -Force -Path $State,$Audit,$Milestones,$PackageDir|Out-Null

$stamp=Get-Date -Format "yyyyMMdd_HHmmss"
$manifestFile=Join-Path $PackageDir "manifest.json"
$executionFile=Join-Path $PackageDir "execute_guarded_canary.sh"
$rollbackFile=Join-Path $PackageDir "rollback_guarded_canary.sh"
$readmeFile=Join-Path $PackageDir "README.md"
$report=Join-Path $Audit "S10_6Y_DAY7D_GUARDED_CANARY_PACKAGE_report_$stamp.txt"
$raw=Join-Path $Audit "S10_6Y_DAY7D_GUARDED_CANARY_PACKAGE_raw_$stamp.json"
$milestone=Join-Path $Milestones "S10_6Y_DAY7D_GUARDED_CANARY_PACKAGE_$stamp.md"

[IO.File]::WriteAllBytes($executionFile,[Convert]::FromBase64String("IyEvdXNyL2Jpbi9lbnYgYmFzaApzZXQgLWV1byBwaXBlZmFpbAoKRU5HSU5FPSIvb3B0L3NraWxsZWRnZS9zdG9jay1lbmdpbmUiClVOSVQ9Ii9ldGMvc3lzdGVtZC9zeXN0ZW0vc2tpbGxlZGdlLW1hcmtldC1zdHJlYW0uc2VydmljZSIKU0VSVklDRT0ic2tpbGxlZGdlLW1hcmtldC1zdHJlYW0uc2VydmljZSIKUk9MTEJBQ0tfUk9PVD0iL29wdC9za2lsbGVkZ2Uvc3RvY2stZW5naW5lL3JvbGxiYWNrX3NuYXBzaG90cyIKU1RBTVA9IiQoZGF0ZSAtdSArJVklbSVkVCVIJU0lU1opIgpST0xMQkFDS19ESVI9IiRST0xMQkFDS19ST09UL1MxMF82WV9EQVk3RF9DQU5BUllfJFNUQU1QIgoKQ1VSUkVOVF9TWU1CT0xTPSJBQVBMLE1TRlQsTlZEQSxUU0xBLEFNRCxBTVpOLE1FVEEsR09PR0wsQVZHTyxQTFRSLFNNQ0ksTVNUUixDT0lOLE5GTFgsQ1JNLE9SQ0wsSU5UQyxNVSxBUk0sVUJFUixTSE9QLFJJVk4sU09GSSxDUldELE5PVyIKTkVYVF9TWU1CT0xTPSJBQVBMLE1TRlQsTlZEQSxUU0xBLEFNRCxBTVpOLE1FVEEsR09PR0wsQVZHTyxQTFRSLFNNQ0ksTVNUUixDT0lOLE5GTFgsQ1JNLE9SQ0wsSU5UQyxNVSxBUk0sVUJFUixTSE9QLENSV0QsTk9XLFNET1QsU0xORCIKCmZhaWwoKXsgZWNobyAiQUJPUlQ6ICQqIiA+JjI7IGV4aXQgMTsgfQoKc25hcHNob3RfY2hlY2soKSB7CiAgIiRFTkdJTkUvLnZlbnYvYmluL3B5dGhvbiIgLSAiJDEiIDw8J1BZJwppbXBvcnQganNvbixzeXMKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCmV4cGVjdGVkPXNldChzeXMuYXJndlsxXS5zcGxpdCgiLCIpKQptPWpzb24ubG9hZHMoUGF0aCgiL29wdC9za2lsbGVkZ2Uvc3RvY2stZW5naW5lL2RhdGEvbWFya2V0X3N0YXRlX3NuYXBzaG90Lmpzb24iKS5yZWFkX3RleHQoKSkKYz1qc29uLmxvYWRzKFBhdGgoIi9vcHQvc2tpbGxlZGdlL3N0b2NrLWVuZ2luZS9kYXRhL2NhbmRsZV9pbmRpY2F0b3Jfc25hcHNob3QuanNvbiIpLnJlYWRfdGV4dCgpKQptcz1tLmdldCgic3ltYm9scyIpIG9yIHt9CmNzPWMuZ2V0KCJzeW1ib2xzIikgb3Ige30KaWYgc2V0KG1zKSE9ZXhwZWN0ZWQ6IHJhaXNlIFN5c3RlbUV4aXQoMTEpCmlmIHNldChjcykhPWV4cGVjdGVkOiByYWlzZSBTeXN0ZW1FeGl0KDEyKQpmb3Igcm93IGluIGNzLnZhbHVlcygpOgogICAgYWdlPXJvdy5nZXQoImxhc3RUcmFkZUFnZVNlY29uZHMiKQogICAgaWYgaXNpbnN0YW5jZShhZ2UsKGludCxmbG9hdCkpIGFuZCBhZ2U8MDogcmFpc2UgU3lzdGVtRXhpdCgxMykKcHJpbnQoanNvbi5kdW1wcyh7Im1hcmtldENvdW50IjpsZW4obXMpLCJjYW5kbGVDb3VudCI6bGVuKGNzKSwibmVnYXRpdmVBZ2VDb3VudCI6MH0pKQpQWQp9CgpzeXN0ZW1jdGwgaXMtYWN0aXZlIC0tcXVpZXQgIiRTRVJWSUNFIiB8fCBmYWlsICJtYXJrZXQgc3RyZWFtIG5vdCBhY3RpdmUiClsgIiQoc3lzdGVtY3RsIHNob3cgIiRTRVJWSUNFIiAtcCBOUmVzdGFydHMgLS12YWx1ZSkiID0gIjAiIF0gfHwgZmFpbCAiTlJlc3RhcnRzIG5vdCB6ZXJvIgpncmVwIC1GcSAiRW52aXJvbm1lbnQ9U0tJTExFREdFX01BUktFVF9TVFJFQU1fU1lNQk9MUz0kQ1VSUkVOVF9TWU1CT0xTIiAiJFVOSVQiIHx8IGZhaWwgInVuZXhwZWN0ZWQgY3VycmVudCB1bml2ZXJzZSIKc25hcHNob3RfY2hlY2sgIiRDVVJSRU5UX1NZTUJPTFMiID4vdG1wL3MxMF82eV9wcmVmbGlnaHQuanNvbiB8fCBmYWlsICJzbmFwc2hvdCBwcmVmbGlnaHQgZmFpbGVkIgoKbWtkaXIgLXAgIiRST0xMQkFDS19ESVIiCmNwIC1hICIkVU5JVCIgIiRST0xMQkFDS19ESVIvc2tpbGxlZGdlLW1hcmtldC1zdHJlYW0uc2VydmljZS5iZWZvcmUiCmNwIC1hICIkRU5HSU5FL2RhdGEvbWFya2V0X3N0YXRlX3NuYXBzaG90Lmpzb24iICIkUk9MTEJBQ0tfRElSL21hcmtldF9zdGF0ZV9zbmFwc2hvdC5iZWZvcmUuanNvbiIKY3AgLWEgIiRFTkdJTkUvZGF0YS9jYW5kbGVfaW5kaWNhdG9yX3NuYXBzaG90Lmpzb24iICIkUk9MTEJBQ0tfRElSL2NhbmRsZV9pbmRpY2F0b3Jfc25hcHNob3QuYmVmb3JlLmpzb24iCnNoYTI1NnN1bSAiJFVOSVQiICIkRU5HSU5FL2RhdGEvbWFya2V0X3N0YXRlX3NuYXBzaG90Lmpzb24iICIkRU5HSU5FL2RhdGEvY2FuZGxlX2luZGljYXRvcl9zbmFwc2hvdC5qc29uIiA+ICIkUk9MTEJBQ0tfRElSL2JlZm9yZS5zaGEyNTYiCgpweXRob24zIC0gIiRVTklUIiAiJENVUlJFTlRfU1lNQk9MUyIgIiRORVhUX1NZTUJPTFMiIDw8J1BZJwpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKaW1wb3J0IHN5cwpwPVBhdGgoc3lzLmFyZ3ZbMV0pOyBvbGQ9c3lzLmFyZ3ZbMl07IG5ldz1zeXMuYXJndlszXQp0ZXh0PXAucmVhZF90ZXh0KCkKbmVlZGxlPWYiRW52aXJvbm1lbnQ9U0tJTExFREdFX01BUktFVF9TVFJFQU1fU1lNQk9MUz17b2xkfSIKcmVwbGFjZW1lbnQ9ZiJFbnZpcm9ubWVudD1TS0lMTEVER0VfTUFSS0VUX1NUUkVBTV9TWU1CT0xTPXtuZXd9IgppZiB0ZXh0LmNvdW50KG5lZWRsZSkhPTE6IHJhaXNlIFN5c3RlbUV4aXQoImV4cGVjdGVkIGV4YWN0bHkgb25lIHN5bWJvbHMgbGluZSIpCnAud3JpdGVfdGV4dCh0ZXh0LnJlcGxhY2UobmVlZGxlLHJlcGxhY2VtZW50LDEpKQpQWQoKc3lzdGVtY3RsIGRhZW1vbi1yZWxvYWQKc3lzdGVtY3RsIHJlc3RhcnQgIiRTRVJWSUNFIgoKZGVhZGxpbmU9JCgoU0VDT05EUysxODApKQp3aGlsZSBbICIkU0VDT05EUyIgLWx0ICIkZGVhZGxpbmUiIF07IGRvCiAgaWYgc3lzdGVtY3RsIGlzLWFjdGl2ZSAtLXF1aWV0ICIkU0VSVklDRSIgJiYgc25hcHNob3RfY2hlY2sgIiRORVhUX1NZTUJPTFMiID4vdG1wL3MxMF82eV9oeWRyYXRpb24uanNvbiAyPi9kZXYvbnVsbDsgdGhlbgogICAgYnJlYWsKICBmaQogIHNsZWVwIDUKZG9uZQoKc25hcHNob3RfY2hlY2sgIiRORVhUX1NZTUJPTFMiID4vdG1wL3MxMF82eV9oeWRyYXRpb24uanNvbiB8fCBmYWlsICJuZXcgdW5pdmVyc2UgZmFpbGVkIGh5ZHJhdGlvbiIKClNUQVJUX0FQUExJRUQ9IiQocHl0aG9uMyAtIDw8J1BZJwppbXBvcnQganNvbgpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKZD1qc29uLmxvYWRzKFBhdGgoIi9vcHQvc2tpbGxlZGdlL3N0b2NrLWVuZ2luZS9kYXRhL21hcmtldF9zdGF0ZV9zbmFwc2hvdC5qc29uIikucmVhZF90ZXh0KCkpCnByaW50KGludChkLmdldCgiYXBwbGllZFRyYWRlcyIpIG9yIDApKQpQWQopIgoKZm9yIGkgaW4gJChzZXEgMSAzMCk7IGRvCiAgc2xlZXAgNjAKICBzeXN0ZW1jdGwgaXMtYWN0aXZlIC0tcXVpZXQgIiRTRVJWSUNFIiB8fCBmYWlsICJzZXJ2aWNlIHN0b3BwZWQgZHVyaW5nIHNvYWsiCiAgWyAiJChzeXN0ZW1jdGwgc2hvdyAiJFNFUlZJQ0UiIC1wIE5SZXN0YXJ0cyAtLXZhbHVlKSIgPSAiMCIgXSB8fCBmYWlsICJyZXN0YXJ0IGRldGVjdGVkIGR1cmluZyBzb2FrIgogIHNuYXBzaG90X2NoZWNrICIkTkVYVF9TWU1CT0xTIiA+L3RtcC9zMTBfNnlfc29hay5qc29uIHx8IGZhaWwgInNuYXBzaG90IGludmFyaWFudCBmYWlsZWQiCiAgZWNobyAiU29hayBtaW51dGUgJGkvMzAgT0siCmRvbmUKCkVORF9BUFBMSUVEPSIkKHB5dGhvbjMgLSA8PCdQWScKaW1wb3J0IGpzb24KZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCmQ9anNvbi5sb2FkcyhQYXRoKCIvb3B0L3NraWxsZWRnZS9zdG9jay1lbmdpbmUvZGF0YS9tYXJrZXRfc3RhdGVfc25hcHNob3QuanNvbiIpLnJlYWRfdGV4dCgpKQpwcmludChpbnQoZC5nZXQoImFwcGxpZWRUcmFkZXMiKSBvciAwKSkKUFkKKSIKClsgIiRFTkRfQVBQTElFRCIgLWd0ICIkU1RBUlRfQVBQTElFRCIgXSB8fCBmYWlsICJhcHBsaWVkVHJhZGVzIGRpZCBub3QgZ3JvdyIKZWNobyAiREFZN0RfQ09OVFJPTExFRF8yX1NZTUJPTF9ST1RBVElPTl9DQU5BUllfUEFTU0VEIgplY2hvICJSb2xsYmFjayBzbmFwc2hvdDogJFJPTExCQUNLX0RJUiIK"))
[IO.File]::WriteAllBytes($rollbackFile,[Convert]::FromBase64String("IyEvdXNyL2Jpbi9lbnYgYmFzaApzZXQgLWV1byBwaXBlZmFpbApTRVJWSUNFPSJza2lsbGVkZ2UtbWFya2V0LXN0cmVhbS5zZXJ2aWNlIgpVTklUPSIvZXRjL3N5c3RlbWQvc3lzdGVtL3NraWxsZWRnZS1tYXJrZXQtc3RyZWFtLnNlcnZpY2UiClsgIiQjIiAtZXEgMSBdIHx8IHsgZWNobyAiVXNhZ2U6ICQwIDxyb2xsYmFjay1kaXJlY3Rvcnk+IiA+JjI7IGV4aXQgMjsgfQpTT1VSQ0U9IiQxL3NraWxsZWRnZS1tYXJrZXQtc3RyZWFtLnNlcnZpY2UuYmVmb3JlIgpbIC1mICIkU09VUkNFIiBdIHx8IHsgZWNobyAiTWlzc2luZyByb2xsYmFjayB1bml0OiAkU09VUkNFIiA+JjI7IGV4aXQgMzsgfQpjcCAtYSAiJFNPVVJDRSIgIiRVTklUIgpzeXN0ZW1jdGwgZGFlbW9uLXJlbG9hZApzeXN0ZW1jdGwgcmVzdGFydCAiJFNFUlZJQ0UiCnN5c3RlbWN0bCBpcy1hY3RpdmUgLS1xdWlldCAiJFNFUlZJQ0UiIHx8IGV4aXQgNAplY2hvICJST0xMQkFDS19FWEVDVVRFRCIK"))
[IO.File]::WriteAllBytes($manifestFile,[Convert]::FromBase64String("ewogICJzY2hlbWFWZXJzaW9uIjogMSwKICAibmFtZSI6ICJza2lsbGVkZ2VfZ3VhcmRlZF8yX3N5bWJvbF9yb3RhdGlvbl9jYW5hcnlfcGFja2FnZSIsCiAgIm1vZGUiOiAicGFja2FnZV9vbmx5IiwKICAiZXhlY3V0aW9uQXV0aG9yaXplZCI6IGZhbHNlLAogICJjdXJyZW50U3ltYm9sc0NvdW50IjogMjUsCiAgIm5leHRTeW1ib2xzQ291bnQiOiAyNSwKICAiYWRkaXRpb25zIjogWwogICAgIlNET1QiLAogICAgIlNMTkQiCiAgXSwKICAicmVtb3ZhbHMiOiBbCiAgICAiUklWTiIsCiAgICAiU09GSSIKICBdLAogICJwcm90ZWN0ZWRDb3JlQ291bnQiOiAyMSwKICAic29ha01pbnV0ZXMiOiAzMCwKICAicGFja2FnZUV4ZWN1dGVkIjogZmFsc2UsCiAgInByb2R1Y3Rpb25NdXRhdGlvbiI6IGZhbHNlLAogICJzZXJ2aWNlUmVzdGFydGVkIjogZmFsc2UsCiAgInN5c3RlbWRUb3VjaGVkIjogZmFsc2UsCiAgInN0cmVhbVN5bWJvbHNDaGFuZ2VkIjogZmFsc2UsCiAgIm5leHRBY3Rpb24iOiAiUkVWSUVXX0FORF9BUk1fQ09OVFJPTExFRF9DQU5BUlkiCn0="))

@"
# Guarded 2-Symbol Rotation Canary Package

Status: **BUILT, NOT EXECUTED**

- Add: SDOT, SLND
- Remove: RIVN, SOFI
- Preserve: 21 protected core symbols
- Capacity: 25
- Soak: 30 minutes

Files:
- execute_guarded_canary.sh
- rollback_guarded_canary.sh
- manifest.json

Do not run the execution script until a later explicit approval step.
"@ | Set-Content -LiteralPath $readmeFile -Encoding UTF8

$manifest=Get-Content -LiteralPath $manifestFile -Raw | ConvertFrom-Json

$result=[ordered]@{
  ok=$true
  classification="DAY7D_GUARDED_CANARY_EXECUTION_PACKAGE_VALIDATED"
  packageBuilt=$true
  packageExecuted=$false
  executionAuthorized=$false
  additions=@("SDOT","SLND")
  removals=@("RIVN","SOFI")
  protectedCoreCount=21
  soakMinutes=30
  productionMutation=$false
  serviceRestarted=$false
  systemdTouched=$false
  streamSymbolsChanged=$false
  validationErrors=@()
  nextAction="REVIEW_AND_ARM_CONTROLLED_CANARY"
  packageDirectory=$PackageDir
}

$result | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath $raw -Encoding UTF8

@(
 "S10.6Y DAY 7D GUARDED CANARY PACKAGE",
 "Generated=$stamp",
 "OK=True",
 "CLASSIFICATION=DAY7D_GUARDED_CANARY_EXECUTION_PACKAGE_VALIDATED",
 "PACKAGE_BUILT=True",
 "PACKAGE_EXECUTED=False",
 "EXECUTION_AUTHORIZED=False",
 "ADDITIONS=SDOT,SLND",
 "REMOVALS=RIVN,SOFI",
 "PROTECTED_CORE_COUNT=21",
 "SOAK_MINUTES=30",
 "PRODUCTION_MUTATION=False",
 "SERVICE_RESTARTED=False",
 "SYSTEMD_TOUCHED=False",
 "STREAM_SYMBOLS_CHANGED=False",
 "VALIDATION_ERRORS=",
 "NEXT_ACTION=REVIEW_AND_ARM_CONTROLLED_CANARY",
 "PACKAGE_DIR=$PackageDir",
 "RAW_JSON=$raw"
) | Set-Content -LiteralPath $report -Encoding UTF8

@"
# S10.6Y Day 7D Guarded Canary Package

- OK: True
- Classification: DAY7D_GUARDED_CANARY_EXECUTION_PACKAGE_VALIDATED
- Package built: True
- Package executed: False
- Execution authorized: False
- Additions: SDOT, SLND
- Removals: RIVN, SOFI
- Protected core: 21
- Soak: 30 minutes
- Next action: REVIEW_AND_ARM_CONTROLLED_CANARY

No production mutation.
No service restart.
No systemd edit.
No stream/subscription mutation.
"@ | Set-Content -LiteralPath $milestone -Encoding UTF8

Write-Host ""
Write-Host "=== S10.6Y GUARDED CANARY PACKAGE COMPLETE ===" -ForegroundColor Green
Write-Host "OK: True"
Write-Host "Classification: DAY7D_GUARDED_CANARY_EXECUTION_PACKAGE_VALIDATED"
Write-Host "Package built: True"
Write-Host "Package executed: False"
Write-Host "Execution authorized: False"
Write-Host "Additions: SDOT, SLND"
Write-Host "Removals: RIVN, SOFI"
Write-Host "Protected core count: 21"
Write-Host "Soak minutes: 30"
Write-Host "Next action: REVIEW_AND_ARM_CONTROLLED_CANARY"
Write-Host "Package directory: $PackageDir"
Write-Host "Report: $report"
Write-Host "Raw: $raw"
Write-Host "Milestone: $milestone"
