from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


ALGORITHM_REGISTRY: list[dict[str, Any]] = [{'id': 'alg_001_premarket_pump_short',
  'setupSlug': 'premarket_pump_short',
  'setupName': 'Premarket Pump Short',
  'family': 'small_cap_pump_short',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': True,
  'executionStatus': 'LIVE_FOUNDATION',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_002_gap_and_crap_short',
  'setupSlug': 'gap_and_crap_short',
  'setupName': 'Gap and Crap Short',
  'family': 'small_cap_pump_short',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': True,
  'executionStatus': 'LIVE_FOUNDATION',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'S5.1 live foundation: detects failed gap/opening drive weakness after a strong move. ACTIVE requires fresh 5m confirmation, true RR >= 2R and A/A+ quality gate.'},
 {'id': 'alg_003_failed_premarket_high_breakout',
  'setupSlug': 'failed_premarket_high_breakout',
  'setupName': 'Failed Premarket High Breakout',
  'family': 'small_cap_pump_short',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_004_lower_high_after_pump',
  'setupSlug': 'lower_high_after_pump',
  'setupName': 'Lower High After Pump',
  'family': 'small_cap_pump_short',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_005_first_red_5m_after_parabolic_push',
  'setupSlug': 'first_red_5m_after_parabolic_push',
  'setupName': 'First Red 5m After Parabolic Push',
  'family': 'small_cap_pump_short',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_006_exhaustion_wick_short',
  'setupSlug': 'exhaustion_wick_short',
  'setupName': 'Exhaustion Wick Short',
  'family': 'small_cap_pump_short',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_007_vwap_stuff_short',
  'setupSlug': 'vwap_stuff_short',
  'setupName': 'VWAP Stuff Short',
  'family': 'small_cap_pump_short',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_008_day_high_stuff_short',
  'setupSlug': 'day_high_stuff_short',
  'setupName': 'Day High Stuff Short',
  'family': 'small_cap_pump_short',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_009_first_fade_after_volume_climax',
  'setupSlug': 'first_fade_after_volume_climax',
  'setupName': 'First Fade After Volume Climax',
  'family': 'small_cap_pump_short',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_010_halt_resume_reclaim_failure',
  'setupSlug': 'halt_resume_reclaim_failure',
  'setupName': 'Reclaim Failure After Halt Resume',
  'family': 'small_cap_pump_short',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_011_dilution_offering_fade',
  'setupSlug': 'dilution_offering_fade',
  'setupName': 'Secondary Offering / Dilution Fade',
  'family': 'small_cap_pump_short',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_012_ssr_trap_fade',
  'setupSlug': 'ssr_trap_fade',
  'setupName': 'SSR Trap Fade',
  'family': 'small_cap_pump_short',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_013_vwap_rejection_short',
  'setupSlug': 'vwap_rejection_short',
  'setupName': 'VWAP Rejection Short',
  'family': 'vwap',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': True,
  'executionStatus': 'LIVE_FOUNDATION',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'S5.2 live foundation: detects VWAP rejection short setups on in-play names. ACTIVE requires fresh 5m VWAP rejection/EMA/lower-high confirmation, true RR >= 2R and A/A+ quality gate.'},
 {'id': 'alg_014_vwap_reclaim_long',
  'setupSlug': 'vwap_reclaim_long',
  'setupName': 'VWAP Reclaim Long',
  'family': 'vwap',
  'assetType': 'stock',
  'direction': 'long',
  'enabled': True,
  'executionStatus': 'LIVE_FOUNDATION',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'S5.3 live foundation: detects reclaim and hold above VWAP/EMA20 after pullback or liquidity reset. ACTIVE requires fresh 5m reclaim confirmation, true RR >= 2R and A/A+ quality gate.'},
 {'id': 'alg_015_vwap_loss_continuation_short',
  'setupSlug': 'vwap_loss_continuation_short',
  'setupName': 'VWAP Loss Continuation Short',
  'family': 'vwap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_016_vwap_bounce_continuation_long',
  'setupSlug': 'vwap_bounce_continuation_long',
  'setupName': 'VWAP Bounce Continuation Long',
  'family': 'vwap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_017_vwap_chop_avoidance_filter',
  'setupSlug': 'vwap_chop_avoidance_filter',
  'setupName': 'VWAP Chop Avoidance Filter',
  'family': 'vwap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_018_vwap_deviation_mean_reversion',
  'setupSlug': 'vwap_deviation_mean_reversion',
  'setupName': 'VWAP Deviation Mean Reversion',
  'family': 'vwap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_019_vwap_ema20_compression_break',
  'setupSlug': 'vwap_ema20_compression_break',
  'setupName': 'VWAP + EMA20 Compression Break',
  'family': 'vwap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_020_vwap_reclaim_after_liquidity_sweep',
  'setupSlug': 'vwap_reclaim_after_liquidity_sweep',
  'setupName': 'VWAP Reclaim After Liquidity Sweep',
  'family': 'vwap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_021_opening_range_breakout_long',
  'setupSlug': 'opening_range_breakout_long',
  'setupName': 'Opening Range Breakout Long',
  'family': 'opening_range',
  'assetType': 'stock',
  'direction': 'long',
  'enabled': True,
  'executionStatus': 'LIVE_FOUNDATION',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'S5.4 live foundation: detects opening range high breakout / trend-day continuation. ACTIVE requires fresh 5m breakout confirmation, structural stop and true RR >= 2R.'},
 {'id': 'alg_022_opening_range_breakdown_short',
  'setupSlug': 'opening_range_breakdown_short',
  'setupName': 'Opening Range Breakdown Short',
  'family': 'opening_range',
  'assetType': 'stock',
  'direction': 'short',
  'enabled': True,
  'executionStatus': 'LIVE_FOUNDATION',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'S5.4 live foundation: detects opening range low loss / failed opening drive. ACTIVE requires fresh 5m breakdown confirmation, structural stop and true RR >= 2R.'},
 {'id': 'alg_023_failed_opening_range_breakout',
  'setupSlug': 'failed_opening_range_breakout',
  'setupName': 'Failed Opening Range Breakout',
  'family': 'opening_range',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_024_failed_opening_range_breakdown',
  'setupSlug': 'failed_opening_range_breakdown',
  'setupName': 'Failed Opening Range Breakdown',
  'family': 'opening_range',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_025_orb_pullback_continuation',
  'setupSlug': 'orb_pullback_continuation',
  'setupName': 'ORB Pullback Continuation',
  'family': 'opening_range',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': True,
  'executionStatus': 'LIVE_FOUNDATION',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'S5.5 live foundation: detects first pullback continuation after opening range breakout/retest. ACTIVE requires fresh 5m confirmation, structural stop and true RR >= 2R.'},
 {'id': 'alg_026_opening_drive_continuation',
  'setupSlug': 'opening_drive_continuation',
  'setupName': 'Opening Drive Continuation',
  'family': 'opening_range',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_027_opening_drive_exhaustion_fade',
  'setupSlug': 'opening_drive_exhaustion_fade',
  'setupName': 'Opening Drive Exhaustion Fade',
  'family': 'opening_range',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_028_first_30m_range_deviation_reversal',
  'setupSlug': 'first_30m_range_deviation_reversal',
  'setupName': 'First 30m Range Deviation Reversal',
  'family': 'opening_range',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_029_news_continuation_pullback_long',
  'setupSlug': 'news_continuation_pullback_long',
  'setupName': 'News Continuation Pullback Long',
  'family': 'gap_catalyst',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_030_news_continuation_pullback_short',
  'setupSlug': 'news_continuation_pullback_short',
  'setupName': 'News Continuation Pullback Short',
  'family': 'gap_catalyst',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_031_gap_hold_continuation_long',
  'setupSlug': 'gap_hold_continuation_long',
  'setupName': 'Gap Hold Continuation Long',
  'family': 'gap_catalyst',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': True,
  'executionStatus': 'LIVE_FOUNDATION',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'S5.5 live foundation: detects gap-hold continuation long when price holds the gap/opening range above VWAP/EMA20. ACTIVE requires fresh 5m continuation confirmation and true RR >= 2R.'},
 {'id': 'alg_032_gap_fill_fade_short',
  'setupSlug': 'gap_fill_fade_short',
  'setupName': 'Gap Fill Fade Short',
  'family': 'gap_catalyst',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_033_earnings_gap_continuation',
  'setupSlug': 'earnings_gap_continuation',
  'setupName': 'Earnings Gap Continuation',
  'family': 'gap_catalyst',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_034_earnings_gap_fade',
  'setupSlug': 'earnings_gap_fade',
  'setupName': 'Earnings Gap Fade',
  'family': 'gap_catalyst',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_035_high_relative_volume_trend_day',
  'setupSlug': 'high_relative_volume_trend_day',
  'setupName': 'High Relative Volume Trend Day',
  'family': 'gap_catalyst',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_036_catalyst_vwap_reclaim',
  'setupSlug': 'catalyst_vwap_reclaim',
  'setupName': 'Catalyst VWAP Reclaim',
  'family': 'gap_catalyst',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_037_failed_breakout_stuff_short',
  'setupSlug': 'failed_breakout_stuff_short',
  'setupName': 'Failed Breakout / Stuff Short',
  'family': 'failed_breakout_trap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_038_failed_breakdown_reclaim_long',
  'setupSlug': 'failed_breakdown_reclaim_long',
  'setupName': 'Failed Breakdown / Reclaim Long',
  'family': 'failed_breakout_trap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_039_liquidity_trap_reversal',
  'setupSlug': 'liquidity_trap_reversal',
  'setupName': 'Liquidity Trap Reversal',
  'family': 'failed_breakout_trap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_040_hod_rejection_short',
  'setupSlug': 'hod_rejection_short',
  'setupName': 'HOD Rejection Short',
  'family': 'failed_breakout_trap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_041_lod_reclaim_long',
  'setupSlug': 'lod_reclaim_long',
  'setupName': 'LOD Reclaim Long',
  'family': 'failed_breakout_trap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_042_equal_highs_sweep_short',
  'setupSlug': 'equal_highs_sweep_short',
  'setupName': 'Equal Highs Sweep Short',
  'family': 'failed_breakout_trap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_043_equal_lows_sweep_long',
  'setupSlug': 'equal_lows_sweep_long',
  'setupName': 'Equal Lows Sweep Long',
  'family': 'failed_breakout_trap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_044_false_break_above_premarket_high',
  'setupSlug': 'false_break_above_premarket_high',
  'setupName': 'False Break Above Premarket High',
  'family': 'failed_breakout_trap',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_045_large_cap_gap_continuation',
  'setupSlug': 'large_cap_gap_continuation',
  'setupName': 'Large Cap Gap Continuation',
  'family': 'large_cap_institutional',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': True,
  'executionStatus': 'LIVE_FOUNDATION',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'S5.6 live foundation: detects institutional large/mega-cap gap continuation when price holds VWAP/EMA20/opening range with fresh 5m confirmation and true RR >= 2R.'},
 {'id': 'alg_046_large_cap_vwap_trend_long',
  'setupSlug': 'large_cap_vwap_trend_long',
  'setupName': 'Large Cap VWAP Trend Long',
  'family': 'large_cap_institutional',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': True,
  'executionStatus': 'LIVE_FOUNDATION',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'S5.6 live foundation: detects liquid large/mega-cap VWAP trend continuation longs with VWAP/EMA20 support, higher-low structure and true RR >= 2R.'},
 {'id': 'alg_047_large_cap_vwap_trend_short',
  'setupSlug': 'large_cap_vwap_trend_short',
  'setupName': 'Large Cap VWAP Trend Short',
  'family': 'large_cap_institutional',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_048_large_cap_earnings_drift',
  'setupSlug': 'large_cap_earnings_drift',
  'setupName': 'Large Cap Earnings Drift',
  'family': 'large_cap_institutional',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_049_large_cap_failed_rally_short',
  'setupSlug': 'large_cap_failed_rally_short',
  'setupName': 'Large Cap Failed Rally Short',
  'family': 'large_cap_institutional',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_050_large_cap_dip_buy_after_flush',
  'setupSlug': 'large_cap_dip_buy_after_flush',
  'setupName': 'Large Cap Dip Buy After Flush',
  'family': 'large_cap_institutional',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_051_mega_cap_trend_pullback',
  'setupSlug': 'mega_cap_trend_pullback',
  'setupName': 'Mega Cap Trend Pullback',
  'family': 'large_cap_institutional',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_052_index_sympathy_momentum',
  'setupSlug': 'index_sympathy_momentum',
  'setupName': 'Index Sympathy Momentum',
  'family': 'large_cap_institutional',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_053_trendline_pullback_structure_continuation',
  'setupSlug': 'trendline_pullback_structure_continuation',
  'setupName': 'Trendline Pullback Structure Continuation',
  'family': 'trend_pullback',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_054_ema20_pullback_continuation_long',
  'setupSlug': 'ema20_pullback_continuation_long',
  'setupName': 'EMA20 Pullback Continuation Long',
  'family': 'trend_pullback',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_055_ema20_rejection_continuation_short',
  'setupSlug': 'ema20_rejection_continuation_short',
  'setupName': 'EMA20 Rejection Continuation Short',
  'family': 'trend_pullback',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_056_higher_low_continuation_long',
  'setupSlug': 'higher_low_continuation_long',
  'setupName': 'Higher Low Continuation Long',
  'family': 'trend_pullback',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_057_lower_high_continuation_short',
  'setupSlug': 'lower_high_continuation_short',
  'setupName': 'Lower High Continuation Short',
  'family': 'trend_pullback',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_058_breakout_retest_long',
  'setupSlug': 'breakout_retest_long',
  'setupName': 'Breakout Retest Long',
  'family': 'trend_pullback',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_059_breakdown_retest_short',
  'setupSlug': 'breakdown_retest_short',
  'setupName': 'Breakdown Retest Short',
  'family': 'trend_pullback',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_060_volume_expansion_continuation',
  'setupSlug': 'volume_expansion_continuation',
  'setupName': 'Volume Expansion Continuation',
  'family': 'trend_pullback',
  'assetType': 'stock',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_061_crypto_liquidity_sweep_reclaim_long',
  'setupSlug': 'crypto_liquidity_sweep_reclaim_long',
  'setupName': 'Liquidity Sweep + Reclaim Long',
  'family': 'crypto_smc_ict',
  'assetType': 'crypto',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_062_crypto_liquidity_sweep_rejection_short',
  'setupSlug': 'crypto_liquidity_sweep_rejection_short',
  'setupName': 'Liquidity Sweep + Rejection Short',
  'family': 'crypto_smc_ict',
  'assetType': 'crypto',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_063_crypto_range_deviation_reversal_long',
  'setupSlug': 'crypto_range_deviation_reversal_long',
  'setupName': 'Range Deviation Reversal Long',
  'family': 'crypto_smc_ict',
  'assetType': 'crypto',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_064_crypto_range_deviation_reversal_short',
  'setupSlug': 'crypto_range_deviation_reversal_short',
  'setupName': 'Range Deviation Reversal Short',
  'family': 'crypto_smc_ict',
  'assetType': 'crypto',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_065_crypto_fvg_rebalance_continuation',
  'setupSlug': 'crypto_fvg_rebalance_continuation',
  'setupName': 'FVG Rebalance Continuation',
  'family': 'crypto_smc_ict',
  'assetType': 'crypto',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_066_crypto_order_block_mitigation_reversal',
  'setupSlug': 'crypto_order_block_mitigation_reversal',
  'setupName': 'Order Block Mitigation Reversal',
  'family': 'crypto_smc_ict',
  'assetType': 'crypto',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_067_crypto_breaker_block_continuation',
  'setupSlug': 'crypto_breaker_block_continuation',
  'setupName': 'Breaker Block Continuation',
  'family': 'crypto_smc_ict',
  'assetType': 'crypto',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'},
 {'id': 'alg_068_crypto_trend_pullback_continuation',
  'setupSlug': 'crypto_trend_pullback_continuation',
  'setupName': 'Trend Pullback Continuation',
  'family': 'crypto_smc_ict',
  'assetType': 'crypto',
  'direction': 'mixed',
  'enabled': False,
  'executionStatus': 'REGISTRY_ONLY',
  'calibrationEnabled': True,
  'minClosedForAdjustment': 10,
  'minSignalsForAdjustment': 20,
  'contextRules': ['centralized_scan', 'volume_liquidity_filter', 'risk_first_validation'],
  'triggerRules': ['setup_specific_confirmation', 'fresh_candle_context', 'rr_min_2r'],
  'riskRules': ['structural_stop', 'true_rr_targets', 'reject_if_tp1_below_zero'],
  'exitRules': ['tp1', 'tp2', 'stop', 'session_close_outcome'],
  'notes': 'Part of SkillEdge 60+ Holly-like algorithm registry. Physical execution is enabled gradually after validation.'}]


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def get_algorithm_registry() -> list[dict[str, Any]]:
    now = utc_now_iso()
    return [
        {
            **item,
            "createdAt": item.get("createdAt") or now,
            "updatedAt": now,
            "registryVersion": "s410_algorithm_registry_v1",
        }
        for item in ALGORITHM_REGISTRY
    ]


def get_algorithm_registry_summary() -> dict[str, Any]:
    items = get_algorithm_registry()
    by_family: dict[str, int] = {}
    by_asset: dict[str, int] = {}
    live_count = 0

    for item in items:
        family = str(item.get("family") or "unknown")
        asset = str(item.get("assetType") or "unknown")
        by_family[family] = by_family.get(family, 0) + 1
        by_asset[asset] = by_asset.get(asset, 0) + 1
        if item.get("executionStatus") == "LIVE_FOUNDATION":
            live_count += 1

    return {
        "ok": True,
        "registryVersion": "s410_algorithm_registry_v1",
        "count": len(items),
        "liveFoundationCount": live_count,
        "registryOnlyCount": len(items) - live_count,
        "byFamily": by_family,
        "byAsset": by_asset,
        "items": items,
    }
